ninox:
  api_url: "https://app.stadtbild.de/v1"
  team_id: "TEAM_ID"
  database_id: "DATABASE_ID"
  table_id: "TABLE_ID"
  persons_table_id: "PERSONS_TABLE_ID"
  api_token: "TOKEN"

smtp:
  host: "smtp.example.com"
  port: 587
  username: "user"
  password: "pass"
  from_address: "todo@example.com"

send_time: "09:00"  # daily notification time
debug: false
debug_user: ""  # when debug is true, send only for this user
